version: '3'

services:
  public:
    image: public
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - yarn:/home/node/.cache/yarn
    tty: true

  server:
    image: caddy/caddy
