apiVersion: extensions/v1beta1

kind: Deployment

metadata:
  name: backend
  labels:
    app: express

spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: express
        tier: backend
    spec:
      containers:
      - name: express-play
        image: gcr.io/[GCLOUD_PROJECT]/express-play
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 3000
        env:
          - name: PROJECT_ID
            value: [GCLOUD_PROJECT]
